name: tash5esy

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.3
  easy_localization: ^3.0.7
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  bottom_picker: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translation/

fonts:
  - family: Lato 
    fonts: 
      - asset: assets/fonts/Lato-Regular.ttf
